name: Database Backup
on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Add PostgreSQL apt repo
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
      - name: Install PostgreSQL 17 client
        run: |
          sudo apt-get install -y postgresql-client-17
      - name: Run backup script
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python3 scripts/backup.py
      - name: Commit & Push backup
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add backups/
          git commit -m "DB Backup $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
