name: Run Database Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy psycopg2-binary alembic bcrypt==4.0.1 passlib[bcrypt]==1.7.4

      - name: Run DB Migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PYTHONPATH: ${{ github.workspace }}   # ✅ ensures imports work
        run: |
          echo ">>> Running database migration..."
          python - <<'PYCODE'
          import os
          import sys
          from sqlalchemy import create_engine
          from sqlalchemy.exc import SQLAlchemyError

          sys.path.append(os.getcwd())

          try:
              from database import Base
              from models import User, GameMatch, WalletTransaction, OTP, Stake
          except ModuleNotFoundError as e:
              print(f"[ERROR] Missing module: {e}")
              sys.exit(1)

          db_url = os.environ["DATABASE_URL"]
          print(f"🔗 Connecting to database... {db_url.split('@')[-1]}")
          engine = create_engine(db_url, echo=False)

          try:
              Base.metadata.create_all(engine)
              print("✅ All tables created successfully:")
              for t in Base.metadata.tables.keys():
                  print(f"   • {t}")
              print("🎉 Migration complete.")
          except SQLAlchemyError as e:
              print(f"[ERROR] Migration failed: {e}")
              sys.exit(1)
          PYCODE
