name: Run Database Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy psycopg2-binary alembic bcrypt==4.0.1 passlib[bcrypt]==1.7.4

      - name: Run DB Migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python - <<'PYCODE'
          import os
          from sqlalchemy import create_engine
          from database import Base
          from models import User, GameMatch, WalletTransaction, OTP, Stake

          print("🔗 Connecting to database...")
          engine = create_engine(os.environ["DATABASE_URL"])
          print("✅ Creating all tables if not exist...")
          Base.metadata.create_all(engine)
          print("🎉 Migration complete. Tables synced with models.")
          PYCODE
