name: Build & Verify FastAPI App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "✅ Dependencies installed successfully"

      - name: Verify bcrypt/passlib versions
        run: |
          python -c "import bcrypt, passlib; print('bcrypt version:', bcrypt.__version__)"
          python -c "from passlib.hash import bcrypt; print('passlib-bcrypt ok:', bcrypt.hash('test123'))"

      - name: Test PostgreSQL connectivity
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python - <<'PYCODE'
          import os, psycopg2
          db = os.environ["DATABASE_URL"]
          conn = psycopg2.connect(db)
          cur = conn.cursor()
          cur.execute("SELECT NOW();")
          print("✅ Database connected:", cur.fetchone())
          conn.close()
          PYCODE

      - name: Validate FastAPI app import
        run: |
          python - <<'PYCODE'
          import importlib
          app = importlib.import_module("main")
          print("✅ FastAPI app loaded:", hasattr(app, "app"))
          PYCODE

      - name: Summary
        run: echo "🎉 Build verified successfully with bcrypt 4.0.1 + passlib 1.7.4"
