name: DB Check
on:
  workflow_dispatch:   # run manually from GitHub Actions tab
  push:
    branches: [ main ] # optional: also run on pushes to main
jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary
      - name: Run DB script
        run: python scripts/list_users.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
