name: Database Backup

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch: # manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client & Python
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Run backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          source venv/bin/activate
          python backup.py

      - name: Push backups
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
