name: Seed Database

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install sqlalchemy psycopg2-binary

      - name: Run DB Seed Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/fix_name_column.py
